services:
  ejabberd:
    hostname: ejabberd
    image: ./ejabberd
    ports:
      - "5443:5443"
      - "5347:5347"
    volumes:
      - ./ejabberd/conf:/home/ejabberd/conf
      - ./data/ejabberd/upload:/home/ejabberd/upload
      - ./data/ejabberd/logs:/home/ejabberd/logs
